In [1]:
from google.colab import drive

# Google Driveをマウント
drive.mount('/content/drive')

# マウント完了後のメッセージ
print("Google Driveがマウントされました！")

Mounted at /content/drive
Google Driveがマウントされました！

In [2]:
import pandas as pd

# TSVファイルをloadする
file_path = '/content/drive/My Drive/signate/train/train.tsv'

# TSVファイルの読み込み
df = pd.read_csv(file_path, low_memory= False,  sep='\t')

# 読み込んだデータを表示
df.head()

,id,click,I1,I2,C1,C2,C3,C4,C5,C6,...,I5,I6,I7,I8,I9,I10,I11,I12,I13,I14
0,0,0,5,20,421256035,2377199148,2696211399,2298910535,3133252034,1509930964,...,0,0,0,0,0,0,NaN,NaN,NaN,780.0
1,1,0,5,20,2581703001,2589684548,1998340283,2411205997,3202148071,1238839469,...,1,1,0,0,0,0,NaN,NaN,NaN,0.0
2,2,0,5,20,2581703001,1862037199,2448089184,2411205997,1107442947,3668889797,...,0,0,0,0,1,0,NaN,NaN,NaN,117.0
3,3,0,5,20,421256035,3874378935,1658216424,2298910535,2321672976,1509930964,...,0,0,0,0,0,0,6.0,6.0,34501.0,390.0
4,4,1,5,20,421256035,3874378935,1892769125,2411205997,2321672976,1509930964,...,0,0,0,0,0,0,1.0,31.0,12557.0,390.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169042 entries, 0 to 1169041
Data columns (total 22 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   id      1169042 non-null  int64
 1   click   1169042 non-null  int64
 2   I1      1169042 non-null  int64
 3   I2      1169042 non-null  int64
 4   C1      1169042 non-null  int64
 5   C2      1169042 non-null  int64
 6   C3      1169042 non-null  int64
 7   C4      1169042 non-null  int64
 8   C5      1169042 non-null  int64
 9   C6      1169042 non-null  int64
 10  I3      1169042 non-null  int64
 11  I4      1169042 non-null  int64
 12  I5      1169042 non-null  int64
 13  I6      1169042 non-null  int64
 14  I7      1169042 non-null  int64
 15  I8      1169042 non-null  int64
 16  I9      1169042 non-null  int64
 17  I10     1169042 non-null  int64
 18  I11     981754 non-null   float64
 19  I12     981754 non-null   float64
 20  I13     981754 non-null   float64
 21  I14     1129422 non-null  float64
dtypes: float64(4), int64(18)
memory usage: 196.2 MB

# 目的変数の分布と基本特徴量を確認する

In [4]:
print(df['click'].value_counts(normalize=True))

print(df.describe())

click
0    0.924941
1    0.075059
Name: proportion, dtype: float64
                 id         click            I1            I2            C1  \
count  1.169042e+06  1.169042e+06  1.169042e+06  1.169042e+06  1.169042e+06
mean   5.845205e+05  7.505889e-02  3.031627e+00  1.220570e+01  1.169567e+09
std    3.374735e+05  2.634865e-01  1.992983e+00  6.139743e+00  1.087105e+09
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  4.212560e+08
25%    2.922602e+05  0.000000e+00  1.000000e+00  7.000000e+00  4.212560e+08
50%    5.845205e+05  0.000000e+00  3.000000e+00  1.300000e+01  4.212560e+08
75%    8.767808e+05  0.000000e+00  5.000000e+00  1.700000e+01  2.581703e+09
max    1.169041e+06  1.000000e+00  6.000000e+00  2.300000e+01  3.651044e+09

                 C2            C3            C4            C5            C6  \
count  1.169042e+06  1.169042e+06  1.169042e+06  1.169042e+06  1.169042e+06
mean   2.381345e+09  2.012817e+09  2.177769e+09  1.888389e+09  2.186933e+09
std    1.099911e+09  1.195821e+09  4.357866e+08  9.501573e+08  9.617819e+08
min    5.393295e+07  2.200363e+07  4.001228e+08  2.446028e+07  1.477335e+08
25%    1.537671e+09  1.025908e+09  2.298911e+09  1.410458e+09  1.509931e+09
50%    1.862037e+09  1.998340e+09  2.411206e+09  2.321673e+09  1.769723e+09
75%    3.874379e+09  2.903162e+09  2.411206e+09  2.321673e+09  3.111152e+09
max    4.218832e+09  4.231334e+09  3.954818e+09  4.272797e+09  4.161523e+09

       ...            I5            I6            I7            I8  \
count  ...  1.169042e+06  1.169042e+06  1.169042e+06  1.169042e+06
mean   ...  3.292790e-01  1.047524e-01  5.746586e-02  8.747077e-02
std    ...  5.794303e+00  3.062343e-01  2.327307e-01  2.825238e-01
min    ...  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%    ...  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
50%    ...  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
75%    ...  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
max    ...  1.965000e+03  1.000000e+00  1.000000e+00  1.000000e+00

                 I9           I10            I11            I12           I13  \
count  1.169042e+06  1.169042e+06  981754.000000  981754.000000  9.817540e+05
mean   3.626439e-01  3.801831e-01     365.767723      14.166252  8.158472e+05
std    4.807635e-01  4.854319e-01    2472.558968      86.252650  1.385875e+06
min    0.000000e+00  0.000000e+00       0.000000       0.000000 -1.000000e+00
25%    0.000000e+00  0.000000e+00       4.000000       1.000000  2.126325e+04
50%    0.000000e+00  0.000000e+00      19.000000       4.000000  1.416105e+05
75%    1.000000e+00  1.000000e+00      84.000000      11.000000  9.316495e+05
max    1.000000e+00  1.000000e+00   58684.000000   32664.000000  1.809308e+07

                I14
count  1.129422e+06
mean   3.624405e+02
std    6.203855e+02
min    0.000000e+00
25%    3.900000e+01
50%    2.600000e+02
75%    3.900000e+02
max    1.300000e+04

[8 rows x 22 columns]

# ユニークな値を確認する

In [ ]:
# 列のユニークな値
print("Unique values in 'I3':", df['I3'].unique())

# 列のユニークな値の総数
unique_count = df['I3'].nunique(dropna=False)

print(f"Total unique values in 'I3': {unique_count}")

Unique values in 'I3': [1 0 2]
Total unique values in 'I3': 3

In [ ]:
print(df.groupby('C1')['click'].mean())
print(df.groupby('C4')['click'].mean())
print(df.groupby('C6')['click'].mean())

C1
421256035     0.096847
1045405899    0.028566
1111213504    0.039077
2068315619    0.119345
2387281372    0.032790
2541535031    0.046566
2581703001    0.032466
2686811630    0.022040
3651044092    0.031724
Name: click, dtype: float64
C4
400122826     0.021935
1332932160    0.113452
1404944795    0.068966
1825710598    0.064510
2298910535    0.072711
2411205997    0.065479
3954817824    0.377528
Name: click, dtype: float64
C6
147733495     0.034488
1238839469    0.073614
1410751928    0.112839
1479325723    0.033869
1509930964    0.088030
1769722553    0.063406
1802588585    0.027972
1991667031    0.059382
2068230268    0.040931
2141877921    0.044108
2798684489    0.037675
3016268466    0.062222
3111151614    0.055194
3668889797    0.127731
3684013252    0.031501
4161523369    0.046025
Name: click, dtype: float64

# 目的変数と特徴量の相関性を確認する

In [ ]:
from scipy.stats import spearmanr

corr_c2, _ = spearmanr(df['C2'], df['click'])
print(f"Spearman Correlation for C2: {corr_c2}")

Spearman Correlation for C2: 0.005414952681673704

# カテゴリ値の前処理

In [5]:
#C1=9、C4=7、C6=16はユニークな値がすくないのでカテゴリ変数にする
columns_to_convert = ['C1', 'C4', 'C6']

for col in columns_to_convert:
    df[col] = df[col].astype('category')


#ユニークな値がC2=171、C3=347、C5=223と多いので、出現頻度を計算し、それを数値として使用する
columns_to_encode = ['C2', 'C3', 'C5']

for col in columns_to_encode:
    freq = df[col].value_counts(normalize=True)  # 正規化された出現頻度
    df[f'{col}_freq'] = df[col].map(freq)

# クラスタリングアルゴリズムを使用して、自動的に出現頻度をグルーピングする

from sklearn.cluster import KMeans
import numpy as np

# KMeansで自動的にグループを生成
# 各列に対して適切なクラスタ数を設定
columns_to_group = {
    'C2_freq': 5,  # C2は5分割
    'C3_freq': 5,  # C3は5分割
    'C5_freq': 3   # C5は3分割
}

for col, n_clusters in columns_to_group.items():
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    df[f'{col}_group'] = kmeans.fit_predict(df[[col]])
    df[f'{col}_group'] = df[f'{col}_group'].astype('category')  # カテゴリ型に変換


#df.drop(columns=['C2', 'C3', 'C5'], inplace=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169042 entries, 0 to 1169041
Data columns (total 28 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   id             1169042 non-null  int64
 1   click          1169042 non-null  int64
 2   I1             1169042 non-null  int64
 3   I2             1169042 non-null  int64
 4   C1             1169042 non-null  category
 5   C2             1169042 non-null  int64
 6   C3             1169042 non-null  int64
 7   C4             1169042 non-null  category
 8   C5             1169042 non-null  int64
 9   C6             1169042 non-null  category
 10  I3             1169042 non-null  int64
 11  I4             1169042 non-null  int64
 12  I5             1169042 non-null  int64
 13  I6             1169042 non-null  int64
 14  I7             1169042 non-null  int64
 15  I8             1169042 non-null  int64
 16  I9             1169042 non-null  int64
 17  I10            1169042 non-null  int64
 18  I11            981754 non-null   float64
 19  I12            981754 non-null   float64
 20  I13            981754 non-null   float64
 21  I14            1129422 non-null  float64
 22  C2_freq        1169042 non-null  float64
 23  C3_freq        1169042 non-null  float64
 24  C5_freq        1169042 non-null  float64
 25  C2_freq_group  1169042 non-null  category
 26  C3_freq_group  1169042 non-null  category
 27  C5_freq_group  1169042 non-null  category
dtypes: category(6), float64(7), int64(15)
memory usage: 202.9 MB

# 数値変数の前処理
今回のデータは匿名化されたデータであり、元々の意味がカテゴリ情報である可能性が高いです。可視化してユニーク値の数が少ない、分布が均等である場合、カテゴリ変数に変換したのですが、うまくいきませんでした。分布から右テールの長い特徴量にのみ、対数変換を適用しました。

In [7]:
import numpy as np

# 対数変換を適用したい列リスト
columns_to_log_transform = ['I5', 'I11', 'I12', 'I13', 'I14']

for col in columns_to_log_transform:
    # 欠損値を中央値で補完
    if df[col].isnull().any():
        print(f"{col} に欠損値が {df[col].isnull().sum()} 個含まれています。補完を行います。")
        df[col] = df[col].fillna(df[col].median())

    # 0以下の値を小さな正の値に置き換える（安全策）
    if (df[col] <= 0).any():
        print(f"{col} に 0 以下の値が含まれています。クリッピングを行います。")
        df[col] = df[col].clip(lower=1e-6)

    # 対数変換を適用
    df[col] = np.log1p(df[col])

    # 確認
    print(f"{col} の処理後: 欠損値数={df[col].isnull().sum()}, 最小値={df[col].min()}")

I5 に 0 以下の値が含まれています。クリッピングを行います。
I5 の処理後: 欠損値数=0, 最小値=9.999995000003334e-07
I11 に欠損値が 187288 個含まれています。補完を行います。
I11 に 0 以下の値が含まれています。クリッピングを行います。
I11 の処理後: 欠損値数=0, 最小値=9.999995000003334e-07
I12 に欠損値が 187288 個含まれています。補完を行います。
I12 に 0 以下の値が含まれています。クリッピングを行います。
I12 の処理後: 欠損値数=0, 最小値=9.999995000003334e-07
I13 に欠損値が 187288 個含まれています。補完を行います。
I13 に 0 以下の値が含まれています。クリッピングを行います。
I13 の処理後: 欠損値数=0, 最小値=9.999995000003334e-07
I14 に欠損値が 39620 個含まれています。補完を行います。
I14 に 0 以下の値が含まれています。クリッピングを行います。
I14 の処理後: 欠損値数=0, 最小値=9.999995000003334e-07

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169042 entries, 0 to 1169041
Data columns (total 28 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   id             1169042 non-null  int64
 1   click          1169042 non-null  int64
 2   I1             1169042 non-null  int64
 3   I2             1169042 non-null  int64
 4   C1             1169042 non-null  category
 5   C2             1169042 non-null  int64
 6   C3             1169042 non-null  int64
 7   C4             1169042 non-null  category
 8   C5             1169042 non-null  int64
 9   C6             1169042 non-null  category
 10  I3             1169042 non-null  int64
 11  I4             1169042 non-null  int64
 12  I5             1169042 non-null  float64
 13  I6             1169042 non-null  int64
 14  I7             1169042 non-null  int64
 15  I8             1169042 non-null  int64
 16  I9             1169042 non-null  int64
 17  I10            1169042 non-null  int64
 18  I11            1169042 non-null  float64
 19  I12            1169042 non-null  float64
 20  I13            1169042 non-null  float64
 21  I14            1169042 non-null  float64
 22  C2_freq        1169042 non-null  float64
 23  C3_freq        1169042 non-null  float64
 24  C5_freq        1169042 non-null  float64
 25  C2_freq_group  1169042 non-null  category
 26  C3_freq_group  1169042 non-null  category
 27  C5_freq_group  1169042 non-null  category
dtypes: category(6), float64(8), int64(14)
memory usage: 202.9 MB

In [9]:
# 列のユニークな値
print("Unique values in 'I10':", df['I10'].unique())

# 列のユニークな値の総数
unique_count = df['I10'].nunique(dropna=False)

print(f"Total unique values in 'I10': {unique_count}")

Unique values in 'I10': [0 1]
Total unique values in 'I10': 2

## OneHotEncodingを適用する

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import joblib  # エンコーダーの保存用
import os
import pandas as pd

# カテゴリ列を再指定
categorical_columns = ['I1', 'C1', 'C4', 'C6', 'I3', 'I4',
                       'I6', 'I7', 'I8', 'I9', 'I10',
                       'C2_freq_group', 'C3_freq_group', 'C5_freq_group']

# 存在するカテゴリ列のみを対象
categorical_columns = list(set(categorical_columns).intersection(df.columns))

# カテゴリ型を明示する
for col in categorical_columns:
    if col in df.columns:
        df[col] = df[col].astype('category')

# One-Hot Encoding の初期化
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# カテゴリ列のエンコーディング
X_categorical = encoder.fit_transform(df[categorical_columns])

# エンコーダーを保存
joblib.dump(encoder, "one_hot_encoder.pkl")

# エンコーディングされたデータを DataFrame に変換
encoded_columns = encoder.get_feature_names_out(categorical_columns)
X_categorical_df = pd.DataFrame(X_categorical, columns=encoded_columns, index=df.index)

# 元データフレームからカテゴリ列を削除し、エンコーディング結果を結合
X = df.drop(columns=categorical_columns).reset_index(drop=True)
X = pd.concat([X, X_categorical_df.reset_index(drop=True)], axis=1)

# 保存先のディレクトリを指定
output_dir = "/content/drive/My Drive/signate/train"
os.makedirs(output_dir, exist_ok=True)  # ディレクトリが存在しない場合は作成

# 保存ファイル名を指定
output_file = os.path.join(output_dir, "train_1228.tsv")

# データセットを保存 (TSV形式)
X.to_csv(output_file, sep='\t', index=False)

print(f"データセットが保存されました: {output_file}")

データセットが保存されました: /content/drive/My Drive/signate/train/train_1226_encoding.tsv

In [10]:
import os

# 保存先のディレクトリを指定
output_dir = "/content/drive/My Drive/signate/train"
os.makedirs(output_dir, exist_ok=True)  # ディレクトリが存在しない場合は作成

# 保存ファイル名を指定
output_file = os.path.join(output_dir, "train_0101.tsv")

# データセットを保存 (TSV形式)
df.to_csv(output_file, sep='\t', index=False)

print(f"データセットが保存されました: {output_file}")

データセットが保存されました: /content/drive/My Drive/signate/train/train_0101.tsv

In [11]:
df.head()

,id,click,I1,I2,C1,C2,C3,C4,C5,C6,...,I11,I12,I13,I14,C2_freq,C3_freq,C5_freq,C2_freq_group,C3_freq_group,C5_freq_group
0,0,0,5,20,421256035,2377199148,2696211399,2298910535,3133252034,1509930964,...,2.995732,1.609438,11.860843,6.660575e+00,0.005017,0.002353,0.002588,2,3,1
1,1,0,5,20,2581703001,2589684548,1998340283,2411205997,3202148071,1238839469,...,2.995732,1.609438,11.860843,9.999995e-07,0.123006,0.064278,0.019702,4,2,1
2,2,0,5,20,2581703001,1862037199,2448089184,2411205997,1107442947,3668889797,...,2.995732,1.609438,11.860843,4.770685e+00,0.222245,0.133608,0.000839,3,0,1
3,3,0,5,20,421256035,3874378935,1658216424,2298910535,2321672976,1509930964,...,1.945910,1.945910,10.448773,5.968708e+00,0.257679,0.047051,0.343521,0,4,0
4,4,1,5,20,421256035,3874378935,1892769125,2411205997,2321672976,1509930964,...,0.693147,3.465736,9.438113,5.968708e+00,0.257679,0.136384,0.343521,0,0,0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169042 entries, 0 to 1169041
Data columns (total 28 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   id             1169042 non-null  int64
 1   click          1169042 non-null  int64
 2   I1             1169042 non-null  int64
 3   I2             1169042 non-null  int64
 4   C1             1169042 non-null  category
 5   C2             1169042 non-null  int64
 6   C3             1169042 non-null  int64
 7   C4             1169042 non-null  category
 8   C5             1169042 non-null  int64
 9   C6             1169042 non-null  category
 10  I3             1169042 non-null  int64
 11  I4             1169042 non-null  int64
 12  I5             1169042 non-null  float64
 13  I6             1169042 non-null  int64
 14  I7             1169042 non-null  int64
 15  I8             1169042 non-null  int64
 16  I9             1169042 non-null  int64
 17  I10            1169042 non-null  int64
 18  I11            1169042 non-null  float64
 19  I12            1169042 non-null  float64
 20  I13            1169042 non-null  float64
 21  I14            1169042 non-null  float64
 22  C2_freq        1169042 non-null  float64
 23  C3_freq        1169042 non-null  float64
 24  C5_freq        1169042 non-null  float64
 25  C2_freq_group  1169042 non-null  category
 26  C3_freq_group  1169042 non-null  category
 27  C5_freq_group  1169042 non-null  category
dtypes: category(6), float64(8), int64(14)
memory usage: 202.9 MB

In [ ]:

# テストデータのエンコーディング
# test_path = '/kaggle/input/test-data-preprocessing/preprocessed_test.csv'
# test_df = pd.read_csv(test_path, low_memory=False)

# テストデータのカテゴリ列を補完
# for col in categorical_columns:
    #if col in test_df.columns:
        #test_df[col].fillna('missing', inplace=True)

# 保存したエンコーダーをロード
#encoder = joblib.load("one_hot_encoder.pkl")

# テストデータのカテゴリ列をエンコーディング
#test_categorical = encoder.transform(test_df[categorical_columns])

# エンコーディング結果を DataFrame に変換
#test_categorical_df = pd.DataFrame(test_categorical, columns=encoded_columns, index=test_df.index)

# 元のテストデータフレームからカテゴリ列を削除し、エンコーディング結果を結合
#test_df = test_df.drop(columns=categorical_columns).reset_index(drop=True)
#test_df = pd.concat([test_df, test_categorical_df.reset_index(drop=True)], axis=1)